### ISSUE TITLE
moodle_url does not need $CFG->wwwroot

### ISSUE THREAD

**Issue by mudrd8mz** [anayleeloolxp/moodle-block_tb_m_slots#1]
I noticed you often use `moodle_url` class as in

```
new moodle_url($CFG->wwwroot . '/blocks/tb_m_slots/js/owl.carousel.js')
```

Please note that `moodle_url` does not need the wwwroot prefix as it adds it automatically. So it is expected to be used as in

```
new moodle_url('/blocks/tb_m_slots/js/owl.carousel.js')
```

**Comment by anayleeloolxp** [comment]
Fixed.
