### ISSUE TITLE
Missing function name prefix

### ISSUE THREAD

**Issue by mudrd8mz** [anayleeloolxp/moodle-block_tb_m_slots#2]
Moodle core often loads lib.php from all present plugins.

Your lib.php loads locallib.php

Your locallib.php contains functions named like

https://github.com/anayleeloolxp/moodle-block_tb_m_slots/blob/f9230333b13d151dd430f9189920ea62553153c1/locallib.php#L31

which violates https://docs.moodle.org/dev/Plugin_contribution_checklist#Namespace_collisions as such functions get loaded into the main scope.

Please note, it would be much cleaner to have this callback implemented as a static method of an autoloaded class. That way, it would be loaded if and only if it is actually needed in settings.php.

**Comment by anayleeloolxp** [comment]
Fixed, have changed the name of the function to block_tb_m_slots_updateconf
