### ISSUE TITLE
Terminology: Benefits Spots vs Marketing slots

### ISSUE THREAD

**Issue by mudrd8mz** [anayleeloolxp/moodle-block_tb_m_slots#4]
The block is called "Benefits Slots" and yet the LEELOO XP UI refers to the feature as "Marketing slots". It took me a while to realise that it is actually the same feature.

**Comment by anayleeloolxp** [comment]
Hi @mudrd8mz 
The name is changed from Marketing slots to Benefits Slots in Leeloo LXP UI as well. So issue is fixed.
